spring:
  # 多环境配置文件
  profiles:
    active: dev
# session共享    
  session:
    storeType: redis
# @ResponseBody
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
# 缓存
  cache:
    type: redis
# AOP
  aop:
    proxy-target-class: true
    auto: true
  
# 分页 page helper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
# 压缩,这个属性样板打开了压缩选项，这样稍后应用到JSON正文的压缩就有保证了。
server:
  compression:
    enabled: true
    mime-types: application/json
    


    
    


